### ISSUE TITLE
Redirect spiel.how to www.spiel.how

### ISSUE THREAD

**Issue by edrogers** [JoshKarpel/spiel#191]
It looks like the DNS settings aren't forwarding requests for [spiel.how](http://spiel.how) over to www.spiel.how

IIUC, .how is a Google-provided TLD, so I assume they are your registrar & DNS provider. If so, here's a StackOverflow comment from a year ago about how to "Add a forwarding address" as Google terms it: https://stackoverflow.com/a/70527251

**Comment by JoshKarpel** [comment]
Nice catch! DNS is pretty mysterious to me...

I set it up a little differently because it looks like the "Add a forwarding address" method completely overrides existing DNS settings (I've been using just a `CNAME` record), so I tried adding an `A` record based on https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain , and I think it's working:

```
$ dig www.spiel.how +nostats +nocomments +nocmd
;www.spiel.how.                 IN      A
www.spiel.how.          5947    IN      CNAME   joshkarpel.github.io.
joshkarpel.github.io.   3055    IN      A       185.199.111.153
joshkarpel.github.io.   3055    IN      A       185.199.108.153
joshkarpel.github.io.   3055    IN      A       185.199.109.153
joshkarpel.github.io.   3055    IN      A       185.199.110.153

$ dig spiel.how +nostats +nocomments +nocmd
;spiel.how.                     IN      A
spiel.how.              6646    IN      A       185.199.109.153
spiel.how.              6646    IN      A       185.199.108.153
spiel.how.              6646    IN      A       185.199.110.153
spiel.how.              6646    IN      A       185.199.111.153
```

The redirect seems to be working correctly in my browser (Chrome).

Could you confirm on your end?

**Comment by edrogers** [comment]
Works for me!

**Comment by JoshKarpel** [comment]
Huzzah! Thanks for the suggestion!
